import Nav from "@components/Nav";
import "@styles/globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { GlobalAuthContextProvider } from "@contextAPI/authContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en">
            <body className={inter.className}>
                <GlobalAuthContextProvider>
                    <Nav />
                    {children}
                </GlobalAuthContextProvider>
            </body>
        </html>
    );
}
