import Nav from "@components/Nav";
import "@styles/globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import AuthContext from "@contextAPI/authContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en">
            <AuthContext>
                <body className={inter.className}>
                    <Nav />
                    {children}
                </body>
            </AuthContext>
        </html>
    );
}
